"""sync existant

Revision ID: 31be4fb0b227
Revises: 
Create Date: 2026-03-08 13:46:50.118614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31be4fb0b227'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('test_question_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_options_question'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_questions', ['test_question_id'], ['id'])

    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('candidate_documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('fk_documents_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    with op.batch_alter_table('candidate_educations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_educations_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_experiences_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_account_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_profiles_account'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_accounts', ['candidate_account_id'], ['id'])

    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_skills_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    with op.batch_alter_table('personality_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('personality_test_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_personality_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    with op.batch_alter_table('personality_tests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('test_session_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('test_question_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('answer_option_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_answers_session'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answers_option'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_sessions', ['test_session_id'], ['id'])
        batch_op.create_foreign_key(None, 'answer_options', ['answer_option_id'], ['id'])

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('personality_test_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_questions_test'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'personality_tests', ['personality_test_id'], ['id'])

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('personality_test_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'in_progress'"))
        batch_op.drop_constraint(batch_op.f('fk_sessions_profile'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_profiles', ['candidate_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sessions_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'in_progress'"))
        batch_op.alter_column('personality_test_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_test'), 'personality_tests', ['personality_test_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('personality_test_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answers_option'), 'answer_options', ['answer_option_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_answers_session'), 'test_sessions', ['test_session_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('answer_option_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('test_question_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('test_session_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('personality_tests', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('personality_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_personality_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('personality_test_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_skills_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_profiles_account'), 'candidate_accounts', ['candidate_account_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('candidate_account_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_experiences_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_educations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_educations_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documents_profile'), 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('candidate_profile_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_options_question'), 'test_questions', ['test_question_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('test_question_id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
