"""add email verification

Revision ID: 4c331e434447
Revises: 9aba3cea9dbb
Create Date: 2026-03-05 13:32:16.706968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c331e434447'
down_revision = '9aba3cea9dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
