"""add personality test module

Revision ID: 9aba3cea9dbb
Revises: 92cb3610fd26
Create Date: 2026-03-05 11:52:32.923643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aba3cea9dbb'
down_revision = '92cb3610fd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personality_test_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personality_test_id'], ['personality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_question_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_question_id'], ['test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('personality_test_id', sa.UUID(), nullable=False),
    sa.Column('ouverture_curiosite', sa.Integer(), nullable=True),
    sa.Column('discipline_fiabilite', sa.Integer(), nullable=True),
    sa.Column('influence_presence', sa.Integer(), nullable=True),
    sa.Column('cooperation', sa.Integer(), nullable=True),
    sa.Column('resilience_stress', sa.Integer(), nullable=True),
    sa.Column('drive_motivation', sa.Integer(), nullable=True),
    sa.Column('style_action', sa.Integer(), nullable=True),
    sa.Column('alignement_strategique', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['personality_test_id'], ['personality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('personality_test_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['personality_test_id'], ['personality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_session_id', sa.UUID(), nullable=False),
    sa.Column('test_question_id', sa.UUID(), nullable=False),
    sa.Column('answer_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_option_id'], ['answer_options.id'], ),
    sa.ForeignKeyConstraint(['test_question_id'], ['test_questions.id'], ),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_answers')
    op.drop_table('test_sessions')
    op.drop_table('personality_profiles')
    op.drop_table('answer_options')
    op.drop_table('test_questions')
    op.drop_table('personality_tests')
    # ### end Alembic commands ###
