"""update candidate profile structure

Revision ID: e24c137ff57c
Revises: 9c9801ea7db0
Create Date: 2026-03-05 09:21:15.638098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24c137ff57c'
down_revision = '9c9801ea7db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_account_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('Homme', 'Femme', 'Autre', name='gender_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('main_field', sa.String(length=150), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_account_id'], ['candidate_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_account_id')
    )
    op.create_table('candidate_educations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('has_prior_experience', sa.Boolean(), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('target_industry', sa.String(length=150), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('target_job_title', sa.String(length=150), nullable=True),
    sa.Column('target_job_level', sa.String(length=100), nullable=True),
    sa.Column('expected_salary_min', sa.Integer(), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('open_to_relocation', sa.Boolean(), nullable=True),
    sa.Column('current_location', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_skills')
    op.drop_table('candidate_experiences')
    op.drop_table('candidate_educations')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
